version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dynamodb
      - postgres
      # - mongodb
      # - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development

  dynamodb:
    image: 'amazon/dynamodb-local'
    ports:
      - '8000:8000'

  postgres:
    image: postgres:14.1
    environment:
      # - POSTGRES_MULTIPLE_DATABASES=atlantic_development,$POSTGRES_DB
      POSTGRES_DB: atlantic_development
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
  #     MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
  #     MONGO_INITDB_DATABASE: local_legend_db
  #   ports:
  #     - '27017:27017'

  # mongodb-seed:
  #   image: mongo:5
  #   container_name: mongodb-seed
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./mongodb-init:/mongodb-init
  #   links:
  #     - mongodb
  #   command:
  #     mongoimport --host mongodb --db local_legend_db --collection planets --authenticationDatabase admin --username $MONGODB_USERNAME --password $MONGODB_PASSWORD --drop --jsonArray --file /mongodb-init/init.json

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - '6379:6379'

  # postgres:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: $POSTGRES_DB
  #     POSTGRES_USER: $POSTGRES_USER
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD


  # keycloak:
  #     image: quay.io/keycloak/keycloak:latest
  #     environment:
  #       DB_VENDOR: POSTGRES
  #       DB_ADDR: postgres
  #       DB_DATABASE: $POSTGRES_DB
  #       DB_USER: $POSTGRES_USER
  #       DB_SCHEMA: public
  #       DB_PASSWORD: $POSTGRES_PASSWORD
  #       KEYCLOAK_USER: $KEYCLOAK_USER
  #       KEYCLOAK_PASSWORD: $KEYCLOAK_PASSWORD
  #     ports:
  #       - 8080:8080
  #     depends_on:
  #       - postgres
        
# volumes:
#   postgres_data:
#     driver: local
  # gem_cache:
