name: Analysis(rubocop, brakeman)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '17 19 * * 3'


jobs:
  rubocop:
    name: Rubocop scan
    env:
      RUBOCOP_VERSION: 1.24.1
      RUBOCOP_PERFORMANCE_VERSION: 1.13.1
      RUBOCOP_RSPEC_VERSION: 2.7.0
      CODE_SCANNING_RUBOCOP_VERSION: 0.5.0
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
        with:
          ruby-version: 3.0
      
      - name: Install rubocop
        run: bundle add rubocop --version ${{env.RUBOCOP_VERSION}} --skip-install

      - name: Install Code Scanning integration
        run: bundle add code-scanning-rubocop --version ${{env.CODE_SCANNING_RUBOCOP_VERSION}} --skip-install

      - name: Install rubocop extensions
        run: |
          bundle add rubocop-rspec --version ${{env.RUBOCOP_RSPEC_VERSION}} --skip-install
          bundle add rubocop-performance --version ${{env.RUBOCOP_PERFORMANCE_VERSION}} --skip-install

      - name: Install app dependencies
        run: bundle install

      - name: Rubocop run
        run: |
          bash -c "
            bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
            [[ $? -ne 2 ]]
          "

      - name: Upload Sarif output
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rubocop.sarif

  brakeman-scan:
    name: Brakeman Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
      with:
        ruby-version: '2.7'

    - name: Setup Brakeman
      env:
        BRAKEMAN_VERSION: '5.2.0'
      run: |
        gem install brakeman --version $BRAKEMAN_VERSION

    - name: Scan
      continue-on-error: true
      run: |
        brakeman -f sarif -o output.sarif.json .

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: output.sarif.json




